service: mirrordns
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - .git/**
    - .gitignore
    - "*~"
provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: prd
  vpc:
    securityGroupIds:
     - sg-65bba82e
    subnetIds:
     - subnet-095db83861e14358f

  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - "ec2:CreateNetworkInterface"
       - "ec2:DescribeNetworkInterfaces"
       - "ec2:DeleteNetworkInterface"
      Resource:
        - Fn::Join:
          - ":"
          - - "arn:aws:ec2"
            - "Ref" : "AWS::Region"
            - "Ref" : "AWS::AccountId"
            - "*"
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
        - "route53:ListResourceRecordSets"
      Resource: "*"

functions:
  update_dns:
    handler: update_dns.update
    environment:
      LOGLEVEL: info
      DOMAIN: cedargatepartners.pvc
      SERVERIP: 10.1.64.64
      ZONEID: Z1YFCFKEPCF88G
    events:
      - schedule: cron(0/11 * * * ? *)


